# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  google_account: <%= ENV["GOOGLE_ACCOUNT"] %>
  dropbox_app_key: <%= ENV["DROPBOX_APP_KEY"] %>
  dropbox_app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
  dropbox_user_token: <%= ENV["DROPBOX_USER_TOKEN"] %>
  dragonfly_secret: <%= ENV["DRAGONFLY_SECRET"] %>

development:
  <<: *defaults

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults

test:
  <<: *defaults
  secret_key_base: secret key base
  google_client_id: google client id
  google_client_secret: google client secret
  google_account: foo@bar.com
